### ISSUE TITLE
При избиране на приятели или спонсори падащото меню се чупи.

### ISSUE THREAD

**Issue by titlextechnology** [initLab/initlanesis#25]
![selection_004](https://cloud.githubusercontent.com/assets/6095375/4385402/15d743d2-43c4-11e4-96b1-103b35af3e8a.png)

**Comment by vlood** [comment]
Страницата отсъства. След преправянето на сайта вероятно пак ще стигнем до момента да хвалим някъде нашите приятели и спонсори, тогава се надявам да нямаме такива драми с менютата.
